# Generated by Django 3.0.1 on 2019-12-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_auto_20191220_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
